with bc as (select GOOGLE_PRODUCT_ID,
       GTIN,
       SITE_NAME as seller_name,
       PRICE,
       PRODUCT_URL as SELLER_PRODUCT_URL
from ANALYTICS.FWS_STAGING.BLACKCURVE_RECENT_COMPETITOR_PRICES
where SITE_NAME in ('Water Softeners & Filters',
                                    'WaterFilters.NET',
                                    'SupplyHouse.com',
                                    'QC Supply',
                                    'FiltersFast.com',
                                    'SuperWater.com',
                                    'KlearWaterStore.com',
                                    'DiscountFilterStore.com',
                                    'RestaurantSupply.com',
                                    'H2O Distributors',
                                    'efilters.net',
                                    'Serv-A-Pure',
                                    'Water Softeners & Filters',
                                    'IceMachinesPLus.co',
                                    'RestaurantTory',
                                    'ABestKitchen Restaurant Equipment',
                                    'WebstaurantStore.com',
                                    'Walmart - DiscountFilterStore',
                                    'Walmart - IPW Industries Inc.',
                                    'Sears - Catch All',
                                    'Walmart - AMI Ventures Inc',
                                    'Sears',
                                    'Zoro',
                                    'U.S. Plastic Corporation',
                                    'Parts Town',
                                    'PlumbersStock.com',
                                    'ESPWaterProducts.com',
                                    'Safe Water Essentials',
                                    'WaterFiltersFAST.com',
                                    'KitchenRestock.com',
                                    'Hotel Restaurant Supply',
                                    'PartsGopher',
                                    'SpaDepot.com',
                                    'Wild West Pool Supplies',
                                    'Hot Tub Warehouse',
                                    'MasterSpaParts.com',
                                    'GetPoolParts.com',
                                    'WECO Filters',
                                    'Restaurant Equipment World',
                                    'High Pressure Pumps & Parts',
                                    'Kleen-Rite Corp',
                                    'American Copper & Brass')
qualify row_number() over(partition by GTIN, SITE_NAME order by PRODUCT_ID desc) = 1
order by GTIN, SITE_NAME asc ),


dataforse as (select GOOGLE_PRODUCT_ID,
       GTIN,
       SELLER_NAME,
       BASE_PRICE as price,
       SELLER_PRODUCT_URL
from ANALYTICS.FWS_STAGING.DATAFORSEO_LATEST_SELLERS
where SELLER_NAME in ('Water Softeners & Filters',
                                    'WaterFilters.NET',
                                    'SupplyHouse.com',
                                    'QC Supply',
                                    'FiltersFast.com',
                                    'SuperWater.com',
                                    'KlearWaterStore.com',
                                    'DiscountFilterStore.com',
                                    'RestaurantSupply.com',
                                    'H2O Distributors',
                                    'efilters.net',
                                    'Serv-A-Pure',
                                    'Water Softeners & Filters',
                                    'IceMachinesPLus.co',
                                    'RestaurantTory',
                                    'ABestKitchen Restaurant Equipment',
                                    'WebstaurantStore.com',
                                    'Walmart - DiscountFilterStore',
                                    'Walmart - IPW Industries Inc.',
                                    'Sears - Catch All',
                                    'Walmart - AMI Ventures Inc',
                                    'Sears',
                                    'Zoro',
                                    'U.S. Plastic Corporation',
                                    'Parts Town',
                                    'PlumbersStock.com',
                                    'ESPWaterProducts.com',
                                    'Safe Water Essentials',
                                    'WaterFiltersFAST.com',
                                    'KitchenRestock.com',
                                    'Hotel Restaurant Supply',
                                    'PartsGopher',
                                    'SpaDepot.com',
                                    'Wild West Pool Supplies',
                                    'Hot Tub Warehouse',
                                    'MasterSpaParts.com',
                                    'GetPoolParts.com',
                                    'WECO Filters',
                                    'Restaurant Equipment World',
                                    'High Pressure Pumps & Parts',
                                    'Kleen-Rite Corp',
                                    'American Copper & Brass')
qualify row_number() over(partition by GTIN, SELLER_NAME order by SCRAPED_AT desc) =1 ),

union_join as (select * from bc

union

select * from dataforse )

select count(*)
from union_join